//! Build the knowledge-graph context file consumed by a PTY-spawned agent (ADR-032).
//!
//! [`GraphContextAssembler`] gathers nodes from the knowledge graph plus shared
//! agent-guidance rules and writes the result to the agent's working directory
//! as `CLAUDE.md` (Claude Code) or `AGENTS.md` (every other supported agent).
//! The file is the only context-handoff mechanism in the PTY model — agents read
//! it on startup, the same way `cd`-ing into a project does today.
//!
//! When a shim source directory is configured via [`GraphContextAssembler::with_shim_dir`],
//! `write_context_file` also copies the per-agent extension shim files into the session
//! directory and appends shim activation instructions to the context file.

use crate::acp::registry::SystemAgentRegistry;
use crate::agent_guidance::{NODE_REFERENCE_FORMAT, SCHEMA_CREATION_RULES, TOOL_STRATEGY_RULES};
use crate::agent_types::{AgentType, ContextError, ContextFile};
use nodespace_core::models::Node;
use nodespace_core::services::NodeEmbeddingService;
use nodespace_core::NodeService;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;

/// Default token budget when none is specified by the caller.
const DEFAULT_TOKEN_BUDGET: u32 = 50_000;

/// ~4 chars/token heuristic — verified within 10% of real tokenizers for
/// typical English markdown content.
const CHARS_PER_TOKEN: u32 = 4;

/// Maximum character length for selected (seed) nodes.
const SEED_NODE_CONTENT_LIMIT: usize = 2000;

/// Maximum character length for semantic-neighbor nodes.
const NEIGHBOR_CONTENT_LIMIT: usize = 500;

/// Semantic neighbours fetched per seed node.
const NEIGHBORS_PER_SEED: usize = 5;

/// Similarity threshold for semantic search.
const SEMANTIC_THRESHOLD: f32 = 0.3;

/// Header explaining what the context file is and how to read it.
const CONTEXT_HEADER: &str = "\
# NodeSpace Knowledge Graph Context

This file is auto-generated by NodeSpace for each agent session. It captures
the nodes you (the agent) have been given and the immediate graph context
around them. Treat the sections below as the authoritative starting point.
";

/// Markdown section appended to the context file when NodeSpace tools are registered.
const TOOLS_SECTION: &str = "\
## NodeSpace Tools

NodeSpace knowledge graph tools are available. Use them to search documentation,
create notes, and update the graph during this session.

Tools available: `nodespace_search_semantic`, `nodespace_get_node`, \
`nodespace_create_node`, `nodespace_update_node`, `nodespace_get_children`
";

/// Files (relative to the per-agent shim subdirectory) that must be copied into
/// the session directory for each agent type.
fn shim_files_for(agent_type: AgentType) -> &'static [&'static str] {
    match agent_type {
        AgentType::ClaudeCode => &["nodespace-hook.ts"],
        AgentType::Codex => &["nodespace-plugin.ts"],
        AgentType::GeminiCli => &["nodespace-tools.json", "nodespace-handler.ts"],
        AgentType::OpenCode => &["nodespace-plugin.ts"],
        AgentType::Pi => &["nodespace-adapter.ts"],
    }
}

/// Subdirectory inside the shim source directory for each agent type.
fn shim_subdir_for(agent_type: AgentType) -> &'static str {
    match agent_type {
        AgentType::ClaudeCode => "claude-code",
        AgentType::Codex => "codex",
        AgentType::GeminiCli => "gemini",
        AgentType::OpenCode => "opencode",
        AgentType::Pi => "pi",
    }
}

/// Look up the context-file convention for `agent_type` in [`AGENT_CATALOG`].
///
/// Falls back to [`ContextFile::AgentsMd`] only if `agent_type` is missing
/// from the catalog — which `AgentType` being a closed enum makes impossible
/// today, but the explicit default keeps `write_context_file` infallible if
/// the catalog and enum ever drift.
fn context_file_for(agent_type: AgentType) -> ContextFile {
    SystemAgentRegistry::new()
        .get(agent_type)
        .map(|d| d.context_file)
        .unwrap_or(ContextFile::AgentsMd)
}

fn estimate_tokens(text: &str) -> u32 {
    (text.len() as u32).div_ceil(CHARS_PER_TOKEN)
}

fn truncate_content(content: &str, max_chars: usize) -> String {
    if content.len() <= max_chars {
        content.to_string()
    } else {
        let cut = content.floor_char_boundary(max_chars.saturating_sub(3));
        format!("{}...", &content[..cut])
    }
}

fn node_title(node: &Node) -> String {
    if let Some(ref title) = node.title {
        if !title.is_empty() {
            return title.clone();
        }
    }
    let first_line = node.content.lines().next().unwrap_or("(untitled)");
    let stripped = first_line
        .trim_start_matches('#')
        .trim_start_matches(' ')
        .trim();
    if stripped.is_empty() {
        "(untitled)".to_string()
    } else {
        truncate_content(stripped, 80)
    }
}

fn format_properties(properties: &serde_json::Value) -> Option<String> {
    let obj = properties.as_object()?;
    if obj.is_empty() {
        return None;
    }

    let mut pairs = Vec::new();
    for (key, value) in obj {
        if value.is_null() {
            continue;
        }
        if let Some(inner_obj) = value.as_object() {
            for (inner_key, inner_val) in inner_obj {
                if !inner_val.is_null() {
                    pairs.push(format!(
                        "{}.{}: {}",
                        key,
                        inner_key,
                        format_json_value(inner_val)
                    ));
                }
            }
        } else {
            pairs.push(format!("{}: {}", key, format_json_value(value)));
        }
    }

    if pairs.is_empty() {
        None
    } else {
        Some(pairs.join(", "))
    }
}

fn format_json_value(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(format_json_value).collect();
            format!("[{}]", items.join(", "))
        }
        serde_json::Value::Null => "null".to_string(),
        other => other.to_string(),
    }
}

#[derive(Debug, Clone)]
struct CollectedRelationship {
    from_title: String,
    relationship_type: String,
    to_title: String,
}

/// Assembles per-session knowledge-graph context and writes it to disk.
///
/// Service references are injected so this crate stays decoupled from Tauri's
/// `AppServices`. The desktop-app layer resolves services and constructs the
/// assembler before each agent session starts.
pub struct GraphContextAssembler {
    node_service: Arc<NodeService>,
    embedding_service: Option<Arc<NodeEmbeddingService>>,
    seed_node_ids: Vec<String>,
    token_budget: u32,
    /// Root of the `@nodespace/agent-tools/shims/` directory. When set,
    /// `write_context_file` copies the per-agent shim files into the session
    /// directory and appends tool activation instructions to the context file.
    shim_source_dir: Option<PathBuf>,
}

impl GraphContextAssembler {
    pub fn new(
        node_service: Arc<NodeService>,
        embedding_service: Option<Arc<NodeEmbeddingService>>,
    ) -> Self {
        Self {
            node_service,
            embedding_service,
            seed_node_ids: Vec::new(),
            token_budget: DEFAULT_TOKEN_BUDGET,
            shim_source_dir: None,
        }
    }

    /// Set the seed node IDs to include in the assembled context.
    pub fn with_seed_nodes(mut self, node_ids: Vec<String>) -> Self {
        self.seed_node_ids = node_ids;
        self
    }

    /// Override the token budget used to gate context size.
    pub fn with_token_budget(mut self, budget: u32) -> Self {
        self.token_budget = if budget == 0 {
            DEFAULT_TOKEN_BUDGET
        } else {
            budget
        };
        self
    }

    /// Set the root of the `@nodespace/agent-tools/shims/` directory.
    ///
    /// When set, `write_context_file` copies per-agent shim files into the
    /// session temp directory and appends NodeSpace tool activation
    /// instructions to the context file.
    pub fn with_shim_dir(mut self, dir: PathBuf) -> Self {
        self.shim_source_dir = Some(dir);
        self
    }

    /// Build the context markdown without writing to disk.
    pub async fn assemble_context(&self) -> Result<String, ContextError> {
        // --- Step 1: fetch seed nodes ---
        let mut seed_nodes: Vec<Node> = Vec::new();
        for id in &self.seed_node_ids {
            match self.fetch_node(id).await {
                Ok(node) => seed_nodes.push(node),
                Err(ContextError::NodeNotFound(nid)) => {
                    tracing::warn!("Seed node not found, skipping: {}", nid);
                }
                Err(e) => return Err(e),
            }
        }

        // --- Step 2: semantic expansion (best-effort) ---
        let seed_ids: HashSet<String> = seed_nodes.iter().map(|n| n.id.clone()).collect();
        let semantic_neighbors = match &self.embedding_service {
            Some(embedding_service) => {
                Self::find_semantic_neighbors(embedding_service, &seed_nodes, &seed_ids).await
            }
            None => {
                tracing::info!("Embedding service unavailable, skipping semantic expansion");
                Vec::new()
            }
        };

        // --- Step 3: title map for relationship labels ---
        let mut node_titles: HashMap<String, String> = HashMap::new();
        for node in &seed_nodes {
            node_titles.insert(node.id.clone(), node_title(node));
        }
        for (node, _) in &semantic_neighbors {
            node_titles.insert(node.id.clone(), node_title(node));
        }

        // --- Step 4: 1-hop relationship traversal ---
        let relationships = self.collect_relationships(&seed_nodes, &node_titles).await;

        // --- Step 5: render markdown within token budget ---
        Ok(build_context_markdown(
            &seed_nodes,
            &semantic_neighbors,
            &relationships,
            self.token_budget,
        ))
    }

    /// Assemble the context and write it to `session_dir` as the appropriate
    /// agent context file (`CLAUDE.md` for Claude Code, `AGENTS.md` otherwise).
    ///
    /// If a shim source directory is configured, also copies the per-agent
    /// extension shim files into `session_dir` and appends the NodeSpace tool
    /// activation section to the context file.
    ///
    /// Returns the absolute path of the written context file.
    pub async fn write_context_file(
        &self,
        session_dir: &Path,
        agent_type: AgentType,
    ) -> Result<PathBuf, ContextError> {
        let mut content = self.assemble_context().await?;

        if let Some(ref shim_dir) = self.shim_source_dir {
            write_shim_files(session_dir, agent_type, shim_dir).await?;
            content.push('\n');
            content.push_str(TOOLS_SECTION);
        }

        write_context_to_dir(session_dir, agent_type, &content).await
    }

    async fn fetch_node(&self, node_id: &str) -> Result<Node, ContextError> {
        self.node_service
            .get_node(node_id)
            .await
            .map_err(|e| ContextError::Other(e.into()))?
            .ok_or_else(|| ContextError::NodeNotFound(node_id.to_string()))
    }

    async fn find_semantic_neighbors(
        embedding_service: &NodeEmbeddingService,
        seed_nodes: &[Node],
        seed_ids: &HashSet<String>,
    ) -> Vec<(Node, f64)> {
        let mut seen: HashSet<String> = seed_ids.clone();
        let mut neighbors: Vec<(Node, f64)> = Vec::new();

        for seed in seed_nodes {
            let query = if seed.content.len() > 200 {
                &seed.content[..seed.content.floor_char_boundary(200)]
            } else {
                &seed.content
            };

            if query.trim().is_empty() {
                continue;
            }

            match embedding_service
                .semantic_search_nodes(query, NEIGHBORS_PER_SEED, SEMANTIC_THRESHOLD, None)
                .await
            {
                Ok(results) => {
                    for (node, score) in results {
                        if !seen.contains(&node.id) {
                            seen.insert(node.id.clone());
                            neighbors.push((node, score));
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!("Semantic search failed for seed node '{}': {}", seed.id, e);
                }
            }
        }

        neighbors.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        neighbors
    }

    async fn collect_relationships(
        &self,
        nodes: &[Node],
        node_titles: &HashMap<String, String>,
    ) -> Vec<CollectedRelationship> {
        let mut relationships = Vec::new();

        for node in nodes {
            let from_title = node_titles
                .get(&node.id)
                .cloned()
                .unwrap_or_else(|| node_title(node));

            match self.node_service.get_children(&node.id).await {
                Ok(children) => {
                    for child in &children {
                        let to_title = node_title(child);
                        relationships.push(CollectedRelationship {
                            from_title: from_title.clone(),
                            relationship_type: "has_child".to_string(),
                            to_title,
                        });
                    }
                }
                Err(e) => {
                    tracing::warn!("Failed to get children for node '{}': {}", node.id, e);
                }
            }

            for mention_id in &node.mentions {
                let to_title = node_titles
                    .get(mention_id)
                    .cloned()
                    .unwrap_or_else(|| mention_id.clone());
                relationships.push(CollectedRelationship {
                    from_title: from_title.clone(),
                    relationship_type: "mentions".to_string(),
                    to_title,
                });
            }
        }

        relationships
    }
}

/// Copy per-agent shim files from `shim_source_dir` into `session_dir`.
///
/// Each agent type has a subdirectory under `shim_source_dir` (e.g.
/// `claude-code/`, `gemini/`) containing one or more files that the agent
/// runtime needs to find at session startup. The files are copied verbatim
/// — no compilation step; agents that execute TS natively (via tsx/ts-node)
/// can load them directly.
async fn write_shim_files(
    session_dir: &Path,
    agent_type: AgentType,
    shim_source_dir: &Path,
) -> Result<(), ContextError> {
    let subdir = shim_subdir_for(agent_type);
    let files = shim_files_for(agent_type);

    for filename in files {
        let src = shim_source_dir.join(subdir).join(filename);
        let dst = session_dir.join(filename);
        tokio::fs::copy(&src, &dst).await.map_err(|e| {
            ContextError::WriteFailed(std::io::Error::new(
                e.kind(),
                format!(
                    "failed to copy shim file '{}' to session dir: {}",
                    src.display(),
                    e
                ),
            ))
        })?;
    }

    Ok(())
}

/// Write `content` to the agent's context file inside `session_dir`. Pure
/// file I/O — extracted from [`GraphContextAssembler::write_context_file`]
/// so the naming + write behaviour can be tested without a `NodeService`.
async fn write_context_to_dir(
    session_dir: &Path,
    agent_type: AgentType,
    content: &str,
) -> Result<PathBuf, ContextError> {
    let context_file = context_file_for(agent_type);
    let path = session_dir.join(context_file.filename());
    tokio::fs::write(&path, content).await?;
    Ok(path)
}

fn format_node_section(node: &Node, content_limit: usize) -> String {
    let title = node_title(node);
    let truncated_content = truncate_content(&node.content, content_limit);
    let mut section = format!(
        "#### {} [{}] (id: {})\n{}\n",
        title, node.node_type, node.id, truncated_content
    );

    if let Some(props) = format_properties(&node.properties) {
        section.push_str(&format!("\nProperties: {}\n", props));
    }

    section
}

fn build_context_markdown(
    seed_nodes: &[Node],
    semantic_neighbors: &[(Node, f64)],
    relationships: &[CollectedRelationship],
    token_budget: u32,
) -> String {
    let mut sections: Vec<String> = Vec::new();
    sections.push(CONTEXT_HEADER.to_string());

    // Shared guidance rules (#1089) — always included.
    let guidance = format!(
        "## Guidance\n\n{}\n\n{}\n\n{}\n",
        SCHEMA_CREATION_RULES, TOOL_STRATEGY_RULES, NODE_REFERENCE_FORMAT,
    );
    sections.push(guidance);

    let header_tokens = estimate_tokens(CONTEXT_HEADER);
    let guidance_tokens = estimate_tokens(sections.last().unwrap());
    let mut remaining_budget = token_budget.saturating_sub(header_tokens + guidance_tokens);

    if !seed_nodes.is_empty() {
        let mut selected_section = String::from("## Selected Nodes\n\n");

        for node in seed_nodes {
            let node_section = format_node_section(node, SEED_NODE_CONTENT_LIMIT);
            let section_tokens = estimate_tokens(&node_section);

            if section_tokens > remaining_budget {
                let reduced = format_node_section(node, 500);
                let reduced_tokens = estimate_tokens(&reduced);
                if reduced_tokens <= remaining_budget {
                    selected_section.push_str(&reduced);
                    remaining_budget = remaining_budget.saturating_sub(reduced_tokens);
                }
            } else {
                selected_section.push_str(&node_section);
                remaining_budget = remaining_budget.saturating_sub(section_tokens);
            }
        }

        let section_header_tokens = estimate_tokens("## Selected Nodes\n\n");
        remaining_budget = remaining_budget.saturating_sub(section_header_tokens);
        sections.push(selected_section);
    }

    if !relationships.is_empty() {
        let mut rel_section = String::from("## Relationships\n");
        let rel_header_tokens = estimate_tokens("## Relationships\n");
        remaining_budget = remaining_budget.saturating_sub(rel_header_tokens);

        for rel in relationships {
            let line = format!(
                "- \"{}\" -> {} -> \"{}\"\n",
                rel.from_title, rel.relationship_type, rel.to_title
            );
            let line_tokens = estimate_tokens(&line);
            if line_tokens > remaining_budget {
                break;
            }
            rel_section.push_str(&line);
            remaining_budget = remaining_budget.saturating_sub(line_tokens);
        }

        sections.push(rel_section);
    }

    if !semantic_neighbors.is_empty() {
        let mut neighbor_section = String::from("## Related Context (auto-discovered)\n\n");
        let neighbor_header_tokens = estimate_tokens("## Related Context (auto-discovered)\n\n");
        remaining_budget = remaining_budget.saturating_sub(neighbor_header_tokens);

        for (node, _score) in semantic_neighbors {
            let node_section = format_node_section(node, NEIGHBOR_CONTENT_LIMIT);
            let section_tokens = estimate_tokens(&node_section);

            if section_tokens > remaining_budget {
                break;
            }

            neighbor_section.push_str(&node_section);
            remaining_budget = remaining_budget.saturating_sub(section_tokens);
        }

        sections.push(neighbor_section);
    }

    sections.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- helpers -----------------------------------------------------------

    fn make_test_node(id: &str, node_type: &str, content: &str, title: Option<&str>) -> Node {
        Node {
            id: id.to_string(),
            node_type: node_type.to_string(),
            content: content.to_string(),
            version: 1,
            created_at: chrono::Utc::now(),
            modified_at: chrono::Utc::now(),
            properties: serde_json::json!({}),
            mentions: vec![],
            mentioned_in: vec![],
            title: title.map(|s| s.to_string()),
            lifecycle_status: "active".to_string(),
        }
    }

    // ---- agent_type -> context_file mapping --------------------------------

    #[test]
    fn claude_code_maps_to_claude_md() {
        assert_eq!(
            context_file_for(AgentType::ClaudeCode),
            ContextFile::ClaudeMd
        );
        assert_eq!(ContextFile::ClaudeMd.filename(), "CLAUDE.md");
    }

    #[test]
    fn non_claude_agents_map_to_agents_md() {
        for agent_type in [
            AgentType::Codex,
            AgentType::GeminiCli,
            AgentType::Pi,
            AgentType::OpenCode,
        ] {
            assert_eq!(context_file_for(agent_type), ContextFile::AgentsMd);
        }
        assert_eq!(ContextFile::AgentsMd.filename(), "AGENTS.md");
    }

    // ---- estimate_tokens / truncate_content --------------------------------

    #[test]
    fn estimate_tokens_rounds_up() {
        assert_eq!(estimate_tokens(""), 0);
        assert_eq!(estimate_tokens("12345678"), 2); // 8/4
        assert_eq!(estimate_tokens("Hello"), 2); // ceil(5/4)
    }

    #[test]
    fn truncate_content_short_passthrough() {
        assert_eq!(truncate_content("Hello", 10), "Hello");
    }

    #[test]
    fn truncate_content_long_truncates() {
        let result = truncate_content("Hello World, this is a long string", 15);
        assert!(result.ends_with("..."));
    }

    // ---- node_title --------------------------------------------------------

    #[test]
    fn node_title_uses_title_field_when_present() {
        let node = make_test_node("1", "text", "# heading", Some("My Title"));
        assert_eq!(node_title(&node), "My Title");
    }

    #[test]
    fn node_title_falls_back_to_first_line() {
        let node = make_test_node("1", "text", "# My Heading\nBody", None);
        assert_eq!(node_title(&node), "My Heading");
    }

    #[test]
    fn node_title_empty_content_is_untitled() {
        let node = make_test_node("1", "text", "", None);
        assert_eq!(node_title(&node), "(untitled)");
    }

    // ---- build_context_markdown -------------------------------------------

    #[test]
    fn empty_context_still_includes_header_and_guidance() {
        let markdown = build_context_markdown(&[], &[], &[], 50_000);
        assert!(markdown.contains("# NodeSpace Knowledge Graph Context"));
        assert!(markdown.contains("## Guidance"));
        assert!(markdown.contains("NODE MODEL:"));
        assert!(markdown.contains("TOOL STRATEGY:"));
        assert!(markdown.contains("nodespace://"));
    }

    #[test]
    fn context_includes_seed_nodes() {
        let nodes = vec![
            make_test_node("node-1", "text", "First node content", Some("First Node")),
            make_test_node("node-2", "task", "Second node content", Some("Second Node")),
        ];
        let markdown = build_context_markdown(&nodes, &[], &[], 50_000);

        assert!(markdown.contains("## Selected Nodes"));
        assert!(markdown.contains("First Node"));
        assert!(markdown.contains("[text]"));
        assert!(markdown.contains("Second Node"));
        assert!(markdown.contains("[task]"));
    }

    #[test]
    fn context_includes_relationships() {
        let nodes = vec![make_test_node("n1", "text", "Content", Some("Node One"))];
        let relationships = vec![CollectedRelationship {
            from_title: "Node One".to_string(),
            relationship_type: "mentions".to_string(),
            to_title: "Node Two".to_string(),
        }];

        let markdown = build_context_markdown(&nodes, &[], &relationships, 50_000);
        assert!(markdown.contains("## Relationships"));
        assert!(markdown.contains("\"Node One\" -> mentions -> \"Node Two\""));
    }

    #[test]
    fn context_includes_semantic_neighbors() {
        let seeds = vec![make_test_node("s1", "text", "Seed content", Some("Seed"))];
        let neighbors = vec![(
            make_test_node("n1", "text", "Neighbor content", Some("Neighbor")),
            0.85,
        )];

        let markdown = build_context_markdown(&seeds, &neighbors, &[], 50_000);
        assert!(markdown.contains("## Related Context (auto-discovered)"));
        assert!(markdown.contains("Neighbor"));
    }

    #[test]
    fn budget_enforcement_drops_neighbors_first() {
        let seeds = vec![make_test_node(
            "s1",
            "text",
            &"Seed content. ".repeat(50),
            Some("Important Seed"),
        )];
        let neighbors: Vec<(Node, f64)> = (0..20)
            .map(|i| {
                (
                    make_test_node(
                        &format!("n{}", i),
                        "text",
                        &"Neighbor content. ".repeat(50),
                        Some(&format!("Neighbor {}", i)),
                    ),
                    0.8 - (i as f64 * 0.01),
                )
            })
            .collect();

        let markdown = build_context_markdown(&seeds, &neighbors, &[], 5_000);

        // Seed and guidance should always be present
        assert!(markdown.contains("Important Seed"));
        assert!(markdown.contains("## Guidance"));
        // Budget should not be wildly exceeded (10% tolerance for heuristic).
        let actual = estimate_tokens(&markdown);
        assert!(actual <= 5_500, "{} tokens exceeds 5000+10% budget", actual);
    }

    #[test]
    fn very_large_node_body_is_truncated() {
        let huge = "X".repeat(100_000);
        let node = make_test_node("huge", "text", &huge, Some("Huge"));
        let markdown = build_context_markdown(&[node], &[], &[], 50_000);
        assert!(markdown.len() < 100_000);
        assert!(markdown.contains("Huge"));
    }

    #[test]
    fn format_node_section_includes_properties() {
        let mut node = make_test_node("fmt1", "text", "Body text", Some("Title"));
        node.properties = serde_json::json!({"task": {"status": "done"}});
        let section = format_node_section(&node, 2000);

        assert!(section.contains("#### Title [text] (id: fmt1)"));
        assert!(section.contains("Body text"));
        assert!(section.contains("Properties:"));
        assert!(section.contains("task.status: done"));
    }

    // ---- write_context_to_dir (the body of write_context_file) ------------

    #[tokio::test]
    async fn write_context_to_dir_writes_claude_md_for_claude_code() {
        let temp = tempfile::tempdir().unwrap();
        let path = write_context_to_dir(temp.path(), AgentType::ClaudeCode, "hello")
            .await
            .unwrap();

        assert_eq!(path, temp.path().join("CLAUDE.md"));
        assert_eq!(tokio::fs::read_to_string(&path).await.unwrap(), "hello");
    }

    #[tokio::test]
    async fn write_context_to_dir_writes_agents_md_for_other_agents() {
        for agent_type in [
            AgentType::Codex,
            AgentType::GeminiCli,
            AgentType::Pi,
            AgentType::OpenCode,
        ] {
            let temp = tempfile::tempdir().unwrap();
            let path = write_context_to_dir(temp.path(), agent_type, "hello")
                .await
                .unwrap();

            assert_eq!(
                path,
                temp.path().join("AGENTS.md"),
                "{:?} should write AGENTS.md",
                agent_type
            );
            assert_eq!(tokio::fs::read_to_string(&path).await.unwrap(), "hello");
        }
    }

    #[tokio::test]
    async fn write_context_to_dir_returns_err_when_dir_missing() {
        let temp = tempfile::tempdir().unwrap();
        let missing = temp.path().join("does-not-exist");
        let err = write_context_to_dir(&missing, AgentType::ClaudeCode, "hello")
            .await
            .unwrap_err();

        assert!(matches!(err, ContextError::WriteFailed(_)));
    }

    // ---- shim file mapping -------------------------------------------------

    #[test]
    fn shim_subdir_covers_all_agent_types() {
        for agent_type in [
            AgentType::ClaudeCode,
            AgentType::Codex,
            AgentType::GeminiCli,
            AgentType::Pi,
            AgentType::OpenCode,
        ] {
            let subdir = shim_subdir_for(agent_type);
            assert!(!subdir.is_empty(), "{:?} has empty shim subdir", agent_type);
        }
    }

    #[test]
    fn shim_files_covers_all_agent_types() {
        for agent_type in [
            AgentType::ClaudeCode,
            AgentType::Codex,
            AgentType::GeminiCli,
            AgentType::Pi,
            AgentType::OpenCode,
        ] {
            let files = shim_files_for(agent_type);
            assert!(!files.is_empty(), "{:?} has no shim files", agent_type);
        }
    }

    #[test]
    fn gemini_shim_has_two_files() {
        // Gemini needs both the tool-definition JSON and the handler script.
        let files = shim_files_for(AgentType::GeminiCli);
        assert_eq!(files.len(), 2);
        assert!(files.contains(&"nodespace-tools.json"));
        assert!(files.contains(&"nodespace-handler.ts"));
    }

    // ---- write_shim_files --------------------------------------------------

    #[tokio::test]
    async fn write_shim_files_copies_expected_files() {
        let shim_source = tempfile::tempdir().unwrap();
        let session_dir = tempfile::tempdir().unwrap();

        // Build a minimal shim source tree matching the expected layout.
        let claude_dir = shim_source.path().join("claude-code");
        tokio::fs::create_dir_all(&claude_dir).await.unwrap();
        tokio::fs::write(claude_dir.join("nodespace-hook.ts"), b"// hook")
            .await
            .unwrap();

        write_shim_files(session_dir.path(), AgentType::ClaudeCode, shim_source.path())
            .await
            .unwrap();

        let copied = tokio::fs::read_to_string(session_dir.path().join("nodespace-hook.ts"))
            .await
            .unwrap();
        assert_eq!(copied, "// hook");
    }

    #[tokio::test]
    async fn write_shim_files_copies_both_gemini_files() {
        let shim_source = tempfile::tempdir().unwrap();
        let session_dir = tempfile::tempdir().unwrap();

        let gemini_dir = shim_source.path().join("gemini");
        tokio::fs::create_dir_all(&gemini_dir).await.unwrap();
        tokio::fs::write(gemini_dir.join("nodespace-tools.json"), b"{}")
            .await
            .unwrap();
        tokio::fs::write(gemini_dir.join("nodespace-handler.ts"), b"// handler")
            .await
            .unwrap();

        write_shim_files(session_dir.path(), AgentType::GeminiCli, shim_source.path())
            .await
            .unwrap();

        assert!(session_dir.path().join("nodespace-tools.json").exists());
        assert!(session_dir.path().join("nodespace-handler.ts").exists());
    }

    #[tokio::test]
    async fn write_shim_files_returns_err_when_source_missing() {
        let session_dir = tempfile::tempdir().unwrap();
        let missing = std::path::PathBuf::from("/does/not/exist");

        let err = write_shim_files(session_dir.path(), AgentType::ClaudeCode, &missing)
            .await
            .unwrap_err();

        assert!(matches!(err, ContextError::WriteFailed(_)));
    }

    // ---- tools section in context file ------------------------------------

    #[test]
    fn tools_section_mentions_all_five_tool_names() {
        for tool in [
            "nodespace_search_semantic",
            "nodespace_get_node",
            "nodespace_create_node",
            "nodespace_update_node",
            "nodespace_get_children",
        ] {
            assert!(
                TOOLS_SECTION.contains(tool),
                "TOOLS_SECTION missing tool: {}",
                tool
            );
        }
    }
}
